# Generated by Django 3.1.1 on 2020-09-12 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to='album_covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(upload_to='playlist_covers/%Y/%m/%d/'),
        ),
    ]
