# Generated by Django 3.1.1 on 2020-09-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_song_listenings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='duration',
            new_name='song_duration',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(null=True, upload_to='audio/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
