# Generated by Django 3.1.1 on 2020-09-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0003_song_listenings'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='_audio_file',
            field=models.FileField(null=True, upload_to='audio/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.DurationField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True),
        ),
    ]
