# Generated by Django 3.0.6 on 2020-09-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Client'), (2, 'Artist'), (3, 'Editor')], default=1),
        ),
    ]
